import React from 'react'
import type { Metadata } from "next";

import Navbar from '@/components/Navbar';
import Hero from '@/components/routes/rafting/Hero';
import Package from '@/components/global/Rafting';
import Logo from '@/components/routes/home/Logo'
import Footer from '@/components/Footer';

export const metadata: Metadata = {
    title: "Rafting | Sea Hawk adventures ",
    description: "Generated by create next app",
};


const page = async () => {
    return (
        <>
            <Navbar />
            <main>
                <Hero />
                <Package />
                <Logo />
            </main>
            <Footer />
        </>
    )
}

export default page;