export const feedback = [
    {
        name: "Ashwini Pal",
        username: "@ashwini",
        comment: "Great experience with sea hawk adventure One of the best river team'",
        stars: 5,
    },
    {
        name: "BAD BOYS GAMING",
        username: "@badboysgaming",
        comment: "Bast river rafting in rishikesh",
        stars: 5,
    },
    {
        name: "Sakshi Dumka",
        username: "@sakshi",
        comment: "Best and enjoy the experience 😍",
        stars: 5,
    },
    {
        name: "Raushan kumar Mukhiya",
        username: "@raushan",
        comment: "",
        stars: 5,
    },
    {
        name: "Abhishek Khatri",
        username: "@abhishek",
        comment: "",
        stars: 5,
    },
    {
        name: "Taniya Itani",
        username: "@taniya",
        comment: "Fabulous and fantastic ride. Wonderful experience ✨",
        stars: 5,
    },
    {
        name: "Aman Negi",
        username: "@aman",
        comment: "Very helpful river guides & also very good behavior to all. Nitesh is one who was our River guide, such a good personality and also he helped me a lot to learn kayaking",
        stars: 5,
    },
    {
        name: "Utkarsh Maurya",
        username: "@utkarsh",
        comment: "",
        stars: 5,
    },
    {
        name: "MASTIRAM JAT",
        username: "@mastiram",
        comment: "Best rafting team in rishikesh highly recommend",
        stars: 5,
    },
    {
        name: "Gourav Sharma",
        username: "@gourav",
        comment: "",
        stars: 5,
    },
    {
        name: "Abhishek Thapliyal",
        username: "@abhishek",
        comment: "",
        stars: 5,
    },
    {
        name: "Rana Tree Removal LLC",
        username: "@rana",
        comment: "Sea Hawk provides exceptional rafting and kayaking services in Rishikesh, boasting a highly professional and respectful team. If you are seeking an ideal weekend getaway in Rishikesh, consider contacting them. They offer quality camping, swimming pool, excellent cuisine and a lot more. Highly recommend",
        stars: 5,
    },
    {
        name: "Shaik Mohammed Adnan",
        username: "@shaik",
        comment: "Had a great experience , We got a experienced guide Manish .",
        stars: 5,
    },
    {
        name: "ABRAR AHAMMAD",
        username: "@abrar",
        comment: "It was a great experience and every one was very professional . And guide manish gave us a wonderful experience",
        stars: 5,
    },
    {
        name: "Kashyap Shani",
        username: "@kashyap",
        comment: "",
        stars: 5,
    },
    {
        name: "Dhaval Shani",
        username: "@dhaval",
        comment: "I had two amazing river rafting experiences with Sea Hawk Adventures in Rishikesh.\n\nThe first trip was during summers in June 2024, where I went with 7 friends for a 75 km rafting expedition. Initially planned as a 3-day, 105 km journey, it was shortened to 2 days due to high water levels, but it was still thrilling. Our raft guide, Sandeep Rana and kayak guide, Nitesh Negi was not only incredibly skilled but also hilarious, keeping us entertained throughout the trip with his sense of humour. During this expedition, we had the unique experience of spending about 60% of the time floating in the river without raft, and we also jumped into many rapids, which was both thrilling and exhilarating!\nStay and food during this trip was also great.\nThey ensured a safe and exciting adventure.\n\nThe second trip was in first week of January 2025, when I returned with 10 friends and cousins for a 35 km rafting experience on cold chilly water. Guides on two rafts, Manish and Rohit were great and Nitesh once again added fun to the adventure with his lively personality.\nThe food served was delicious, adding to the overall enjoyment.\n\nBoth times, the experience was unforgettable, and I highly recommend Sea Hawk Adventures for anyone looking to explore the Ganga River in Rishikesh. Special thanks to Rishi, the owner, for being very helpful!",
        stars: 5,
    },
    {
        name: "Sanidhya Shani",
        username: "@sanidhya",
        comment: "Title: Unforgettable Whitewater Adventure!\n\nSeahawk Adventures delivered an absolutely thrilling and unforgettable whitewater rafting experience. From the moment we arrived, the team was incredibly professional, friendly, and safety-conscious. Our guides were experienced and enthusiastic, providing clear instructions and making sure everyone felt comfortable throughout the journey.\n\nThe rapids were exhilarating, and the scenery was breathtaking. We encountered some challenging sections, but our guides handled them with skill and kept the mood fun and exciting. We even had the opportunity to swim in some natural pools and enjoy the stunning surroundings.\n\nSeahawk Adventures clearly prioritize safety and customer satisfaction. They provided all the necessary equipment, and their attention to detail was impressive. I highly recommend Seahawk Adventures to anyone looking for an adrenaline-pumping and unforgettable whitewater rafting adventure.",
        stars: 5,
    },
    {
        name: "Md Tauqueer",
        username: "@tauqueer",
        comment: "We had the pleasure of embarking on a river rafting adventure with Sea Hawk Adventures, and it was truly a remarkable experience! The entire process, from booking to the actual rafting, was seamless and well-organized.",
        stars: 5,
    },
    {
        name: "Akshay Tripathi",
        username: "@akshay",
        comment: "Awesome experience 😃 , had great fun one of the best rafting experience I had.",
        stars: 5,
    },
    {
        name: "Monark Mehta",
        username: "@monark",
        comment: "Great experience",
        stars: 5,
    },
    {
        name: "RAJAN GARG",
        username: "@rajan",
        comment: "",
        stars: 5,
    },
    {
        name: "Aryan Bhardwaj",
        username: "@aryan",
        comment: "Best experience 💯💦.",
        stars: 5,
    },
    {
        name: "Aditya Jha",
        username: "@aditya",
        comment: "",
        stars: 5,
    },
    {
        name: "Ashwani Kumar",
        username: "@ashwani",
        comment: "",
        stars: 5,
    },
    {
        name: "Ronit Mukherjee",
        username: "@ronit",
        comment: "very nice",
        stars: 5,
    },
    {
        name: "Nitesh kumar Singh",
        username: "@nitesh",
        comment: "",
        stars: 5,
    },
    {
        name: "prashant raj",
        username: "@prashant",
        comment: "Beat guide Nitesh bhiya",
        stars: 5,
    },
    {
        name: "SURAJ GAIKWAD",
        username: "@suraj",
        comment: "Had an amazing time rafting with Sea Hawk Adventure. The guides were expertly trained, the equipment was top-notch, and the scenery was breathtaking. Highly recommend !!",
        stars: 5,
    },
    {
        name: "Vikas Choudhary",
        username: "@vikas",
        comment: "",
        stars: 5,
    },
    {
        name: "Ravi Kumar",
        username: "@ravi",
        comment: "Exella raft guide Manish Bhandara",
        stars: 5,
    },
    {
        name: "Manish Bhandari",
        username: "@manish",
        comment: "🙏good fun/totallyprofessional/safe and secure/awesome thanks !!",
        stars: 5,
    },
    {
        name: "Mamta Khadka",
        username: "@mamta",
        comment: "Nice experience",
        stars: 5,
    },
    {
        name: "Trilok Rawat",
        username: "@trilok",
        comment: "good experience best Adventure company in Rishikesh Professional Guide Professional Kayaker Good service.....",
        stars: 5,
    },
    {
        name: "garv Gupta",
        username: "@garv",
        comment: "",
        stars: 5,
    },
    {
        name: "Nitin Dahiya",
        username: "@nitin",
        comment: "Best rafting in rishikesh with sea hawk Great river team",
        stars: 5,
    },
    {
        name: "Nikhil Dahiya",
        username: "@nikhil",
        comment: "Best rafting in Rishikesh with sea hawk",
        stars: 5,
    },
    {
        name: "Arun kumar Kumar",
        username: "@arun",
        comment: "This is my first time for river rafting in rishikesh with friends and enjoy a lot. Very much recommended for river rafting company in rishikesh must visit Sea Hawk Adventures they are very professional team in Rishikesh.",
        stars: 5,
    },
    {
        name: "Sachin Singh",
        username: "@sachin",
        comment: "",
        stars: 5,
    },
    {
        name: "Mahaveer Pundir",
        username: "@mahaveer",
        comment: "Best company in rishikesh we had a lot of fun with the team Sea Hawk adventures.",
        stars: 5,
    },
    {
        name: "jeyashree kothai",
        username: "@jeyashree",
        comment: "Excellent experience..must try… our guide Manish was fantastic",
        stars: 5,
    },
    {
        name: "Saurabh Modi",
        username: "@saurabh",
        comment: "",
        stars: 5,
    },
    {
        name: "Nishan Patel",
        username: "@nishan",
        comment: "Our river rafting experience with Sea Hawk Adventures was truly unforgettable! From the booking process to the actual rafting, everything was seamless.\n\nOur guide, Manish, was fantastic—extremely knowledgeable, skilled, and a lot of fun! His friendly and supportive nature made everyone feel at ease, and his expertise ensured we felt safe while having an amazing time on the river. It was thrilling yet comfortable, and Manish's guidance made it even better. Highly recommend Sea Hawk Adventures for an exhilarating rafting adventure!",
        stars: 5,
    },
    {
        name: "mohan bhadauria",
        username: "@mohan",
        comment: "Best rafting in rishikesh",
        stars: 5,
    },
    {
        name: "Kushagra Gupta",
        username: "@kushagra",
        comment: "we had a good fun and enjoyed a lot thanks to sea hawk team specialy thanks to mr Rishi sir",
        stars: 5,
    },
    {
        name: "Sagar Agrawal",
        username: "@sagar",
        comment: "Rafting experience was really great, they helped us in each and every point. This was my first time and i enjoy very much",
        stars: 5,
    },
    {
        name: "Arjun Kaley",
        username: "@arjun",
        comment: "10/10 Kayak School. I learnt Kayaking from Nitesh, one of the instructors. The instruction was precise, to the point and safety was his utmost priority. Iv become a lifelong client of theirs to learn and grow in white water kayaking.",
        stars: 5,
    },
    {
        name: "Iti Tyagi",
        username: "@iti",
        comment: "I recently went for a rafting expedition with the sea hawk adventures' team. They are very professional and expert in their field. They made our trip enjoyable and memorable keeping our safety as their priority. Thanks to the entire team for the efforts. I'll definitely look forward on to them for my next adventure trip.",
        stars: 5,
    },
    {
        name: "Shivam Tyagi",
        username: "@shivam",
        comment: "I recently went to a Rafting expedition of 100 Km from Upper Bhagirathi to Rishikesh(3N/4D). People say that rafting in Ganga is amazing but with this expedition of 4 Days i realized that it is not the river, it is the people/guides/kayakers who make the journey beautiful and adventurous. Kudos to the entire team of sea hawk Rishi Bhaiya, Sohan Bhaiya, Nitesh, Ankit, Sandeep and many more for giving us the best time during the trip.The camping, rafting, food and every single thing was amazing, Gonna join again on the next expedition to other great rivers of our country.",
        stars: 5,
    },
    {
        name: "Mr Prashant sharma",
        username: "@prashant",
        comment: "Sea Hawk Adventures team is very professional it was great fun .",
        stars: 5,
    },
    {
        name: "Skritant Gaur",
        username: "@skritant",
        comment: "It was great experience with Sea hawk adventure Very professional team they have we had lot of fun. Thank you team",
        stars: 5,
    },
    {
        name: "Rajeev gurjar",
        username: "@rajeev",
        comment: "It was really best rafting in rishikesh we are 6 people and had a good experience with Sea Hawk Adventures",
        stars: 5,
    },
    {
        name: "Barquat Ali",
        username: "@barquat",
        comment: "Best rafting in Rishikesh",
        stars: 5,
    },
    {
        name: "AVINASH PANDAGALE",
        username: "@avinash",
        comment: "Best rafting in Rishikesh👌✌️",
        stars: 5,
    },
    {
        name: "Anchal shukla",
        username: "@anchal",
        comment: "The experience was great.",
        stars: 5,
    },
    {
        name: "Vaibhav Mathur",
        username: "@vaibhav",
        comment: "",
        stars: 5,
    },
    {
        name: "Dinesh Tak",
        username: "@dinesh",
        comment: "",
        stars: 5,
    },
    {
        name: "Aditya Parihar",
        username: "@aditya",
        comment: "One of the best in adventure activities 🔥",
        stars: 5,
    },
    {
        name: "yuvraj sankhla",
        username: "@yuvraj",
        comment: "It was really fantastic rafting experience",
        stars: 5,
    },
    {
        name: "Swapnil Tadas",
        username: "@swapnil",
        comment: "Ultimate experience with Nitesh",
        stars: 5,
    },
    {
        name: "Sagar Tomar",
        username: "@sagar",
        comment: "It was great experience with sea hawk Guide very friendly nitesh bhai",
        stars: 5,
    },
    {
        name: "Sachin Singh",
        username: "@sachin",
        comment: "👍",
        stars: 5,
    },
    {
        name: "Suraj Kumar",
        username: "@suraj",
        comment: "It was great experience with sea hawk adventures gret team work ! Thanks sea hawk team we are planning for next trip",
        stars: 5,
    },
    {
        name: "rupesh sharma",
        username: "@rupesh",
        comment: "",
        stars: 5,
    },
    {
        name: "ANURUDH VERMA",
        username: "@anurudh",
        comment: "",
        stars: 5,
    },
    {
        name: "Hiten 09",
        username: "@hiten",
        comment: "",
        stars: 5,
    },
    {
        name: "Beard Boy Ankur",
        username: "@ankur",
        comment: "Amazong trip….Super se b upar wala Mza AAA gya thx for this amazing trip Sea Hawk Adventure ✌️",
        stars: 5,
    },
    {
        name: "RENU RANA",
        username: "@renu",
        comment: "",
        stars: 5,
    },
    {
        name: "Gabriele Businaro",
        username: "@gabriele",
        comment: "I had a very good time, both for the kayaking and for the rafting",
        stars: 5,
    },
    {
        name: "Deepak Dhankhar",
        username: "@deepak",
        comment: "Excellent staff, highly professional instructors - very helpful & accomodating.",
        stars: 5,
    },
    {
        name: "Meghna Yadav",
        username: "@meghna",
        comment: "",
        stars: 5,
    },
    {
        name: "Mamta Pundir",
        username: "@mamta",
        comment: "Sea hawk adventure is very good you should go there I think you should go there once because it is very good 👍😊",
        stars: 5,
    },
    {
        name: "Devansh Bawari",
        username: "@devansh",
        comment: "I recently had an amazing experience at Sea Hawk Camp in Rishikesh. The rafting adventure was not only thrilling but also well-organized. The entire team, including the owners, ensured our safety and enjoyment throughout. The camp facilities were excellent, providing a comfortable and enjoyable stay. The picturesque surroundings added to the overall charm. I highly recommend Sea Hawk Camp for anyone seeking a memorable rafting and camping experience. Kudos to the owners and the entire team for making our trip so fantastic!",
        stars: 5,
    },
    {
        name: "karan sharma",
        username: "@karan",
        comment: "Best experience very safe and trustful friendly behaviour",
        stars: 5,
    },
];
